language: python

python:

  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -e .
  - wget https://github.com/pints-team/pints/archive/master.zip -O /tmp/pints-master.zip
  - unzip /tmp/pints-master.zip
  - pushd pints-master && ./configure --prefix=/usr && make && sudo make install && popd
script:
    - pytest
